#!/usr/bin/env bash
# use your head

i=1
while [ $i -lt 101 ]
do
	if (( (i%3)==0 ))
	then
		echo "Fizz"
	elif (( (i%5)==0 ))
	then
		echo "Buzz"
	elif (( (i%3)==0 && (i%5)==0 ))
	then
		echo "FizzBuzz"
	else
		echo $i
	fi
	(( i++ ))
done	
