#!/usr/bin/env bash
sudo apt update
sudo apt install ufw -y
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw redirect 8080/tcp to 80/tcp
sudo ufw enable
